FROM python
WORKDIR /usr/src/app

# If requirements contains modules to install
#COPY requirements.txt ./ 
#RUN /bin/sh -c pip install --no-cache-dir -r requirements.txt

COPY . .

# Keeps program running in background until shut down
#CMD ["tail", "-f", "/de#v/null"]